language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.6.3
    - GHCVER=7.8.3
    - GHCVER=head
  global:
    - CABALVER=1.20
    - HEAD_DEPS="diagrams-core"

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - git clone http://github.com/ggreif/dynamic-loader travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

