language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - HPVER=2014.2.0.0
    - GHCVER=7.6.3
    - GHCVER=7.8.2
    - GHCVER=head
  global:
    - CABALVER=1.20

matrix:
  allow_failures:
    - env: GHCVER=head


